# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'zcu102_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'zcu102_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Code_Programmed/Vivado_file/FPGA_CNN/PS_DDR_Project/PS_DDR_Project.srcs/sources_1/bd/zcu102/ip/zcu102_zynq_ultra_ps_e_0_1/zcu102_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
