webtalk_init -webtalk_dir D:\\Code_Programmed\\Vivado_file\\FPGA_CNN\\PS_DDR_Project\\PS_DDR_Project.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-10 15:54:56" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jr3kpedsf7tf2t6v39gvu2ih5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.299 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1575964149363" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key isZynqMP -value "true" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key Processors -value "7" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key Arch -value "zynquplus" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key Device -value "xczu9eg" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1575964149363"
webtalk_add_data -client sdk -key uid -value "1575964278446" -context "sdk\\\\bsp/1575964278446"
webtalk_add_data -client sdk -key hwid -value "1575964149363" -context "sdk\\\\bsp/1575964278446"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1575964278446"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1575964278446"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1575964278446"
webtalk_add_data -client sdk -key uid -value "1575964287389" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key hwid -value "1575964149363" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key bspid -value "1575964278446" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key projSize -value "239.9140625" -context "sdk\\\\application/1575964287389"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1575964496833"
webtalk_transmit -clientid 4176500457 -regid "" -xml D:\\Code_Programmed\\Vivado_file\\FPGA_CNN\\PS_DDR_Project\\PS_DDR_Project.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Code_Programmed\\Vivado_file\\FPGA_CNN\\PS_DDR_Project\\PS_DDR_Project.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Code_Programmed\\Vivado_file\\FPGA_CNN\\PS_DDR_Project\\PS_DDR_Project.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
