webtalk_init -webtalk_dir D:/Code_Programmed/Vivado_file/FPGA_CNN/Native_DDR_project/Native_DDR_project.sim/sim_1/behav/xsim/xsim.dir/ddr4_example_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 10 15:13:21 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "df512a9785bc57eeb406f8a363f8c7c9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9c15629e23ca467a91fbd75f73c81998" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "177" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "70356675 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "50.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "308152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1301567844 -regid "" -xml D:/Code_Programmed/Vivado_file/FPGA_CNN/Native_DDR_project/Native_DDR_project.sim/sim_1/behav/xsim/xsim.dir/ddr4_example_test_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Code_Programmed/Vivado_file/FPGA_CNN/Native_DDR_project/Native_DDR_project.sim/sim_1/behav/xsim/xsim.dir/ddr4_example_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Code_Programmed/Vivado_file/FPGA_CNN/Native_DDR_project/Native_DDR_project.sim/sim_1/behav/xsim/xsim.dir/ddr4_example_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
